### ISSUE TITLE
Example code of Hibernate reactive docs might create another new Vertx instance

### ISSUE THREAD

**Issue by codingxu97** [vertx-howtos/hibernate-reactive-howto#3]
[Hibernate reactive Docs](https://how-to.vertx.io/hibernate-reactive-howto/) seems non-rigorous.It will create a new Vertx instance when I run the example code,and it might cause some operations to be not thread-safe.

![Warn](https://user-images.githubusercontent.com/35094351/137263472-3b951dc9-7744-47d4-8a5d-355dbba82881.png)

**Comment by tsegismont** [comment]
Thank you @Mr-CodingXu

**Comment by codingxu97** [comment]
Hi, @tsegismont .

I had sent a PR to Hibernate Reactive about solving duplicate creation of Vertx instance, reviewer was considering if should merge this before the 1.0.0.Final, so I'm talking with him about it. I think this issue could be solve just to change the version of Hibernate Reactive later.

**Comment by codingxu97** [comment]
> Hi, @tsegismont .
> 
> I had sent a PR to Hibernate Reactive about solving duplicate creation of Vertx instance, reviewer was considering if should merge this before the 1.0.0.Final, so I'm talking with him about it. I think this issue could be solved just to change the version of Hibernate Reactive later.

Hibernate Reactive 1.0.0.Final release, duplicate creation of Vertx instance has been solve.
